googlemaps/js-jest-mocks

src/index.ts, src/places/autocomplete.test.ts, src/places/autocomplete.ts, src/places/searchbox.test.ts, src/places/searchbox.ts
=> feat: add stubs for places widgets (Autocomplete, SearchBox)

.eslintrc.json, src/data.test.ts, src/data.ts, src/index.ts, src/map.ts
As discussed in the linked issue.
PR also includes a config update for eslint to handle EOL differences between Windows and MacOS. Otherwise, the linting will throw an error.
---
Fixes #141 🦕
=> feat:  google.maps.Data object mocks

README.md, src/maps/event/mvcobject.test.ts, src/maps/event/mvcobject.ts, src/maps/maps/map.test.ts
Thank you for opening a Pull Request!
---
Fixes #175  🦕
---
This patch provides accessibility to the class instances that are created as "mocks".  Because each class is defined as such, and not as a jest function, we are not able to retrieve the instances as we normally would in jest:
```typescript
import { Map } from "@googlemaps/jest-mocks";
test('fail', () => {
const mapMock = google.maps.Map as jest.Mock;
expect(mapMock.fitBounds).toHaveBeenCalled();
});
test('success', () => {
const mapMock = Map.mockInstances[0];
expect(mapMock.fitBounds).toHaveBeenCalled();
});
```
An alternative solution, may be to redefine each class a a jest function so that this works more natively, and there is less …
=> feat: instance accessibility for tests

src/index.ts, src/maps/infowindow/infowindow.test.ts, src/maps/infowindow/infowindow.ts
* also adds basic test for new mocks
Thank you for opening a Pull Request!
---
Fixes #181  🦕
=> feat: InfoWindow mocks

src/drawing/kml/kmllayer.test.ts, src/drawing/kml/kmllayer.ts, src/index.ts
Adds KmlLayer mocks and tests
---
Fixes #234  🦕
=> feat: KmlLayer mocks

package-lock.json, src/maps/maps/map.ts
=> fix: initialize map properties

src/index.ts
Sorry I haven't opened an issue for this, I forked the repo to see if exporting the Autocomplete class worked for my testing need.
FYI - this change fixed my problem to allow 
```typescript
beforeEach(() => {
initialize();
});
describe("GooglePlaceAutocomplete", () => {
const callback = jest.fn();
const requiredProps = {
initialValue: undefined,
callback,
};
const renderComponent = (props = requiredProps) =>
render(<GooglePlaceAutocomplete {...props} />);
it("renders", async () => {
renderComponent();
const autoComplete = mockInstances.get(Autocomplete)[0];
act(() => {
autoComplete.addListener.mock.calls[0][1]();
});
await waitFor(() => {
expect(
screen.getByTestId("google-place-autocomplete")
).toBeInTheDocument();
expect(autoComplete.addListener).toBeCalledTimes(1); …
```
=> Export Places Autocomplete and SearchBox

src/index.ts, src/places/autocomplete-service/autocomplete-service.test.ts, src/places/autocomplete-service/autocomplete-service.ts
- Adds autocomplete service mock 
- Adds autocomplete service mock test
Fixes #285  ✨
=> feat: add mock for autocomplete service

src/index.ts
In the last PR I missed adding the LatLngAltitude mock to `initialize()` and exports in index.ts 😅 
Fixes #383 🦕
=> fix: add LatLngAltitude to initialize and exports

src/drawing/data/data.feature.ts, src/drawing/data/data.polygon.test.ts, src/drawing/data/data.polygon.ts, src/drawing/data/data.ts, src/index.ts
Feature: `Data.Polygon` mock, a sub-class of `Data` with methods that are unique from `Polygon`.
https://developers.google.com/maps/documentation/javascript/reference/data#Data.Polygon
To allow `mockInstances.get`, `DataPolygon` is exported.
Bug fix: `Feature` is extended from `MVCObject` so that instances are added to the registry.
---
Fixes #303 🦕
Fixes #304  🦕
=> feat: data.polygon mock and add feature to registry

src/maps/maps/map.ts
`google.maps.Map.getStreetView()` now returns an actual (mock) instance of a Street View panorama.
---
Fixes #324  🦕
=> fix: return actual sv instance for map method

package-lock.json, src/index.ts, src/maps/event/event.ts, src/maps/event/mvcobject.ts, src/maps/maps/featurelayer.ts, src/maps/maps/map.ts, src/street-view/rendering/panorama.ts
The updated `@types/google.maps` version required some changes for new functions added to the API:
- changed type of `Map.controls`
- added `Map.getMapCapabilities()`
- added `Map.getFeatureLayer()`
- added mock for `google.maps.FeatureLayer`
- added `StreetviewPanorama.focus()`
This should allow merging the the open pull-requests (#406, #407 and #408) and make #376, #379 and #403 obsolete.
=> fix: update dependencies

src/drawing/advanced-marker-view/advanced-marker-view.test.ts, src/drawing/advanced-marker-view/advanced-marker-view.ts, src/drawing/advanced-marker-view/pin-view.test.ts, src/drawing/advanced-marker-view/pin-view.ts, src/index.ts
- adds mock for advanced marker view
- adds test for advanced marker view mock
- adds mock for pin view
- adds test for pin view mock
Closes #397 and closes #396 📍
=> feat: add advanced marker view

src/maps/event/event.ts
I missed the `static` modifier in the `google.maps.events` class, this adds them back and cleans up the mock-class.
=> fix: google.maps.events methods were missing static modifier

src/maps/event/event.ts, src/maps/event/mvcobject.ts, src/maps/maps/map.ts, src/street-view/rendering/panorama.ts
- Fixes type errors in different files
- Fixes an eslint error
Fixes #389 🩹
=> fix: typescipt and eslint errors

src/index.ts, src/routes/elevation-service/elevation-service.test.ts, src/routes/elevation-service/elevation-service.ts
- adds mock for elevation service
- adds test for elevation service mock
Closes #394 ⛰
=> feat: add mock elevation service

src/index.ts, src/places/autocomplete-session-token/autocomplete-session-token.test.ts, src/places/autocomplete-session-token/autocomplete-session-token.ts
Hi there - thanks for making a great library!
Previously the `google.maps.places.AutocompleteSessionToken` class was not mocked by this library.
Developers implementing custom autocomplete operations would likely encounter the following error message in their tests:
```
TypeError: google.maps.places.AutocompleteSessionToken is not a constructor
```
This PR adds a mock and exports it for the `AutocompleteSessionToken` class. The constructor accepts no parameters, and the class does not expose any public functions/methods ([docs](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompleteSessionToken)).
resolves #495
---
- ~[] Appropriate docs were …
=> feat(autocomplete): Add AutocompleteSessionToken Mocks

src/routes/directions-service/directions-service.ts
The `response.request` property was missing from the mock implementation, causing typescript errors when compiling and using.
=> fix: DirectionsService.route contains the request in its response

src/import-library.test.ts, src/import-library.ts, src/index.ts
Implemented a mock for importLibrary that returns the correct collection of api-objects in their mocked versions.
closes #468
=> feat: implement mock for importLibrary

src/drawing/advanced-marker-element/advanced-marker-element.test.ts, src/drawing/advanced-marker-element/advanced-marker-element.ts
Add initialization of the `advancedMarkerEl.element` property. In the real API this is initialized in the constructor and is guaranteed to be an html-element, so it has to be here as well.
=> fix: initialize element property of AdvancedMarkerElement

package-lock.json, package.json, src/maps/infowindow/infowindow.ts, src/maps/maps/map.ts
bump @types/google.maps from 3.55.7 to 3.55.11 and adds missing properties to InfoWindow and Map_
I saw there was another pr addressing this issue made some time ago, but it fails on the pipeline, due to missing properties in InfoWindow and Map_ objects. I have fixed everything in this one.
Fixes #711   🦕
=> chore(deps-dev): bump @types/google.maps to 3.55.11, add missing properties to InfoWindow and Map

.eslintrc.json, package-lock.json, rollup.config.mjs
- eslint-update required the now-removed @typescript-eslint/ban-types rule to be configured differently
- rollup-update required the declarationDir to be configured correctly.
=> chore: update dependencies
